# Simple Cloudflare Tunnel Config - BTCPay Only
# Copy this to replace your /etc/cloudflared/config.yml

tunnel: YOUR_TUNNEL_ID
credentials-file: /home/admin/.cloudflared/YOUR_TUNNEL_ID.json

originRequest:
  noTLSVerify: true

ingress:
  # ONLY BTCPay Server exposed publicly
  - hostname: pay.yourdomain.com
    service: http://localhost:80
    
  # Everything else stays private via Tailscale
  # No additional public services - maximum security
  - service: http_status:404